### PR TITLE
feat(pedersen-hash): generate Pedersen Hash params for arbitrary segments

### PR DESCRIPTION
**Pull request by DrPeterVanNostrand**
Adds a function for generating JubJub Pedersen Hash params for any segment/segment range of the Pedersen Hash preimage, not just for the first 5 segments as is currently implemented in `JubjubBls12::new()`. This is necessary for an "updatable" Pedersen Hash where the user wants to hash more than 5 segments worth of data, or wants to hash data as a stream as opposed to all at once as currently implemented.

### CODE REVIEW

**Review by dignifiedquire — COMMENTED** [review]
@arielgabizon could you take a look at this, and make sure this works as expected please?

**Comment by arielgabizon** [comment]
Went over the code with @DrPeterVanNostrand and looks good; but I have a high level question for @porcuquine @dignifiedquire .
How I understand our use case - the column commitments. We will know in advance our number of generators and it will be fixed; if that is the case a simpler code change of changing the constant in Zcash sapling code of num of generators will also do the job.

**Comment by porcuquine** [comment]
That's right, @arielgabizon. We should know in advance the largest number of bits we need to hash. This could potentially be fairly large, with super-sectors, and knowing the cost might be *one* of the factors influencing the target max — so it would be useful to know what the practical limit is. Are we limited by ability to find new generators, or by RAM for the table? If we just increase the constant specifying the number of generators, will that somehow prevent hashing incrementally as new values become available? (I read @DrPeterVanNostrand's comments as suggesting it will — though I'm not sure why.)

**Comment by DrPeterVanNostrand** [comment]
> Are we limited by ability to find new generators, or by RAM for the table?

We aren't limited by the number of generators as the order of the JubJub subgroup is `r = 6554484396890773809930967563523245729705921265872317281365359162392183254199` (as per section 5.4.8.3 of the Zcash spec "Jubjub"). Then `r - 1` is the number of generators.

The number of generators we can generate could potentially be limited by the "hash into Jubjub subgroup" function (section 5.4.8.5 in the zcash spec "Group Hash into Jubjub"). If one of the segment indices does not hash into the prime order subgroup then the generator generation process [would panic](https://github.com/filecoin-project/sapling-crypto/blob/4d7639f041c9cc1785e5364939228f9cb9f5885a/src/jubjub/mod.rs#L237) (we generate each segment's generator by hashing the segment index into the prime order subgroup).

I think that becoming RAM limited is far more likely than not being able to hash into the subgroup, even for large numbers of segments.

> If we just increase the constant specifying the number of generators, will that somehow prevent hashing incrementally as new values become available?

Generating all the generators and exponentiation tables up front (via a constant change) would not prevent incremental hashing, it would just become the caller of `pedersen_hash()`'s responsibility to keep track of the segment index they are hashing for and the generator/exp-tables/Jubjub params associated with the segment index ([this commit](https://github.com/filecoin-project/rust-fil-proofs/commit/0980d4a6329eef0668267f3d55da80c7085923be) in `rust-fil-proofs` more or less implements this tracking functionality). The user would then just pass the correct subset of params into`pedersen_hash()`.

**Comment by porcuquine** [comment]
If we can get away with just increasing the constant for now, that seems preferable. If we later run into RAM usage issues, we might need a more sophisticated way of balancing between window size and number of generators. It's conceivable (or is it?) that this work might help with that problem if it arises. More likely (if this is even an issue), we could solve it by making the caching more sophisticated.

To be clear: I'm only anticipating issues without fully diving into them. Let's keep things as simple as possible and just solve the concrete problems which arise as they do.

If we can do the simple thing here now, while still allowing for updatable hashing of longer preimages, let's do so.

**Pull request closed without merging**
